#!/bin/bash

##
# Acuparse - AcuRite Access/smartHUB and IP Camera Data Processing, Display, and Upload.
# @copyright Copyright (C) 2015-2020 Maxwell Power
# @author Maxwell Power <max@acuparse.com>
# @link http://www.acuparse.com
# @license AGPL-3.0+
#
# This code is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this code. If not, see <http://www.gnu.org/licenses/>.
##

##
# File: cam/templates/local
# Local IP camera upload shell script
##

### USER VALUES ###
CAMERA_HOST='http://'
CAMERA_FILENAME='snapshot.jpg'
WATERMARK='Station Name | Station Web Address'
REMOTE_USER='root'
REMOTE_HOST=''
RESIZE='50%'
### END USER VALUES ###

REMOTE_TMP='/opt/acuparse/cam/tmp'
REMOTE_SCRIPT='/opt/acuparse/cam/remote'
TIMESTAMP=$(date +"%A, %d %B %Y %H:%M %Z")

echo "Getting camera image"
wget ${CAMERA_HOST}/${CAMERA_FILENAME}

echo "Applying Timestamp and Copyright"
convert ${CAMERA_FILENAME} \
-resize ${RESIZE} \
-font DejaVu-Sans-Bold -pointsize 20 \
-draw "gravity south \
        fill black  text 0,36 '$TIMESTAMP' \
        fill OrangeRed2  text 1,37 '$TIMESTAMP' " \
-font DejaVu-Sans-Bold -pointsize 12 \
-draw "gravity south \
        fill black  text 0,0 '$WATERMARK' \
        fill OrangeRed2  text 1,1 '$WATERMARK' " \
image.jpg

echo "Sending image to remote server for processing"
scp image.jpg ${REMOTE_USER}@"${REMOTE_HOST}":${REMOTE_TMP}

echo "Running remote commands"
ssh ${REMOTE_USER}@"${REMOTE_HOST}" 'sh ' ${REMOTE_SCRIPT}

# Local Archiving
# ARCHIVE=$(date +"%F_%H%M")
# echo "Archiving"
# convert ${CAMERA_FILENAME} \
#     -font DejaVu-Sans-Bold -pointsize 16 \
#     -draw "gravity south \
#     fill black  text 0,0 '$TIMESTAMP' \
#     fill OrangeRed2  text 1,1 '$TIMESTAMP' " \
#     archive.jpg
# mv archive.jpg archive/${ARCHIVE}.jpg

echo "Cleaning up files"
rm image.jpg*
rm ${CAMERA_FILENAME}*

echo "Done Processing"
